package simpledb;
import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private JoinPredicate predicate;
    private DbIterator child1;
    private DbIterator child2;
    private Tuple tuple1;

    /**
     * Constructor.  Accepts to children to join and the predicate
     * to join them on
     *
     * @param p The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.predicate = p;
        this.child1 = child1;
        this.child2 = child2;
        this.tuple1 = null;
    }

    /**
     * @see simpledb.TupleDesc#combine(TupleDesc, TupleDesc) for possible implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return TupleDesc.combine(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open()
        throws DbException, NoSuchElementException, TransactionAbortedException {
        child1.open();
        child2.open();
        tuple1 = null;
    }

    public void close() {
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        close();
        open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no more tuples.
     * Logically, this is the next tuple in r1 cross r2 that satisfies the join
     * predicate.  There are many possible implementations; the simplest is a
     * nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of
     * Join are simply the concatenation of joining tuples from the left and
     * right relation. Therefore, if an equality predicate is used 
     * there will be two copies of the join attribute
     * in the results.  (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (tuple1 == null && child1.hasNext()) {
            tuple1 = child1.next();
        }
        while (true) {
            while (child2.hasNext()) {
                Tuple tuple2 = child2.next();
                if (predicate.filter(tuple1, tuple2)) {
                    return Tuple.combine(tuple1, tuple2);
                }
            }
            if (child1.hasNext()) {
                tuple1 = child1.next();
                child2.rewind();
            } else {
                break;
            }
        }
        return null;
    }
    public String getJoinField1Name() {
        return this.child1.getTupleDesc().getFieldName(this.predicate.getField1());
    }

    public String getJoinField2Name() {
        return this.child2.getTupleDesc().getFieldName(this.predicate.getField2());
    }
}
